<?php
/**
 * Do not edit this file. Edit the config files found in the config/ dir instead.
 * This file is required in the root directory so WordPress can find it.
 * WP is hardcoded to look in its own directory or one directory up for wp-config.php (w/o wp-settings.php).
 */

// Define global PATH constants here manually
define('_WEBROOT_DIR_', __DIR__);
define('WP_CORE_DIR', _WEBROOT_DIR_ . '/core');
define('WP_MIRROR_DIR', _WEBROOT_DIR_ . '/mirr');
define('WP_CONTENT_DIR', _WEBROOT_DIR_ . '/app');
define('WP_USERFILES_DIR', _WEBROOT_DIR_ . '/usrfs');
define('_ROOT_DIR_', dirname(__DIR__));
define('_CONFIG_DIR_', _ROOT_DIR_ . '/config');
define('_VENDOR_DIR_', _ROOT_DIR_ . '/vendor');

// Wordpress basic constants
define('ABSPATH', WP_CORE_DIR . '/');

// Load basic config parameters
##require_once(WP_MIRROR_DIR . '/symlnmirror.php');
require_once(_VENDOR_DIR_ . '/autoload.php');
require_once(_CONFIG_DIR_ . '/application.php');

/**
 * Get the SITEURL from the incoming server parameters
 */
function _is_ssl() {
	// Enhanced version of is_ssl() for proxied/loadbalanced https detection
	if ( isset($_SERVER['HTTPS']) ) {
		if ( 'on' == strtolower($_SERVER['HTTPS']) )
			return true;
		if ( '1' == $_SERVER['HTTPS'] )
			return true;
	} elseif ( isset($_SERVER['SERVER_PORT']) && ( '443' == $_SERVER['SERVER_PORT'] ) ) {
		return true;
	} 
	
	if (isset($_SERVER['HTTP_X_FORWARDED_PROTO'])) {
		if ( 'https' == strtolower($_SERVER['HTTP_X_FORWARDED_PROTO']) )
			return true;
	} elseif (isset($_SERVER['HTTP_X_FORWARDED_SSL'])) {
		if ( 'on' == strtolower($_SERVER['HTTP_X_FORWARDED_SSL']) )
			return true;
	} elseif ( isset($_SERVER['HTTP_X_FORWARDED_PORT']) && ( '443' == $_SERVER['HTTP_X_FORWARDED_PORT'] ) ) {
		return true;
	} 

	return false;
}

function _get_dynvhost() {
	// Enhanced version of is_ssl() for proxied/loadbalanced https detection
	if ( isset($_SERVER['HTTP_HOST']) ) {
		return $_SERVER['HTTP_HOST'];
	} elseif ( isset($_SERVER['HTTP_X_FORWARDED_HOST']) ) {
		return $_SERVER['HTTP_X_FORWARDED_HOST'];
	} 
	
	if ( isset($_SERVER['HTTP_X_FORWARDED_SERVER']) ) {
		return $_SERVER['HTTP_X_FORWARDED_SERVER'];
	} elseif ( isset($_SERVER['SERVER_NAME']) ) {
		return $_SERVER['SERVER_NAME'];
	} 

	return ROOT_DOMAIN;
}

function _get_wpmuhome() {

	$schema = _is_ssl() ? 'https://' : 'http://'; 
	$wpmuhost = _get_dynvhost();

	return rtrim($schema . $wpmuhost, '/');
}


// Load other config parameters
require_once(_CONFIG_DIR_ . '/relocation.php');
#require_once(_CONFIG_DIR_ . '/multinetwork.php');
#require_once(_CONFIG_DIR_ . '/rebranding.php');
require_once(WP_CORE_DIR . '/wp-settings.php');

